# gen_build_info.cmake
# Runs at build time (via add_custom_target) to generate build_info.h.
# Called with:
#   -DCMAKE_SOURCE_DIR=<repo root>
#   -DOUTPUT_FILE=<path to build_info.h>

# --- Branch name ---
execute_process(
    COMMAND git rev-parse --abbrev-ref HEAD
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE GIT_RESULT
)

if(NOT GIT_RESULT EQUAL 0 OR GIT_BRANCH STREQUAL "HEAD" OR GIT_BRANCH STREQUAL "")
    set(GIT_BRANCH "unknown")
endif()

# --- Dirty state ---
execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

if(NOT GIT_STATUS STREQUAL "")
    set(GIT_BRANCH "${GIT_BRANCH} (dirty)")
endif()

# --- Username ---
set(BUILD_USERNAME "$ENV{USER}")
if(BUILD_USERNAME STREQUAL "")
    set(BUILD_USERNAME "unknown")
endif()

# --- Write header ---
file(WRITE "${OUTPUT_FILE}"
"/* Auto-generated by gen_build_info.cmake — do not edit */
#ifndef BUILD_INFO_H
#define BUILD_INFO_H
#define BUILD_GIT_BRANCH \"${GIT_BRANCH}\"
#define BUILD_USERNAME   \"${BUILD_USERNAME}\"
#endif  // BUILD_INFO_H
")
